# Generated by Django 2.0.2 on 2018-03-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180313_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commander',
            name='primary_role',
        ),
        migrations.RemoveField(
            model_name='commander',
            name='secondary_role',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='call_sign',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='livery',
        ),
        migrations.AddField(
            model_name='commander',
            name='role1',
            field=models.IntegerField(choices=[(0, 'Explorer'), (1, 'Fuel Rat'), (2, 'Miner'), (3, 'Fleet Mechanic'), (4, 'Tour Guide'), (5, 'Astrophotographer'), (6, 'Fighter Escort'), (7, 'Geologist'), (8, 'Scientist'), (9, 'Media'), (10, 'MediCorp'), (11, 'Fleet Logistics')], default=0, verbose_name='Primary Role'),
        ),
        migrations.AddField(
            model_name='commander',
            name='role2',
            field=models.IntegerField(choices=[(0, 'Explorer'), (1, 'Fuel Rat'), (2, 'Miner'), (3, 'Fleet Mechanic'), (4, 'Tour Guide'), (5, 'Astrophotographer'), (6, 'Fighter Escort'), (7, 'Geologist'), (8, 'Scientist'), (9, 'Media'), (10, 'MediCorp'), (11, 'Fleet Logistics')], null=True, verbose_name='Secondary Role'),
        ),
        migrations.AddField(
            model_name='ship',
            name='ship_id',
            field=models.CharField(default=0, max_length=6, verbose_name='Ship ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commander',
            name='cmdr_name',
            field=models.CharField(max_length=25, null=True, verbose_name='Commander Name'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='comms_id',
            field=models.CharField(max_length=15, null=True, verbose_name='Comms Nickname'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='dwe_veteran',
            field=models.BooleanField(default=False, verbose_name='Participated in DWE 3302'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='platform',
            field=models.CharField(max_length=8, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='roster_num',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Roster Number'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='timezone',
            field=models.CharField(max_length=8, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='visited_beagle_point',
            field=models.BooleanField(default=False, verbose_name='Has visited Beagle Point'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='model',
            field=models.CharField(choices=[('adder', 'Adder'), ('conda', 'Anaconda'), ('aspx', 'Asp Explorer'), ('asps', 'Asp Scout'), ('beluga', 'Beluga Liner'), ('chieftain', 'Chieftain'), ('cobra3', 'Cobra Mk III'), ('cobra4', 'Cobra Mk IV'), ('dbx', 'Diamondback Explorer'), ('dbs', 'Diamondback Scout'), ('dolphin', 'Dolphin'), ('eagle', 'Eagle Mk II'), ('fas', 'Federal Assault Ship'), ('corvette', 'Federal Corvette'), ('dropship', 'Federal Dropship'), ('gunship', 'Federal Gunship'), ('fdl', 'Fer-De-Lance'), ('hauler', 'Hauler'), ('clipper', 'Imperial Clipper'), ('courier', 'Imperial Courier'), ('cutter', 'Imperial Cutter'), ('ieagle', 'Imperial Eagle'), ('keelback', 'Keelback'), ('krait', 'Krait'), ('orca', 'Orca'), ('python', 'Python'), ('sidewinder', 'Sidewinder Mk I'), ('t10', 'Type-10 Defender'), ('t6', 'Type-6 Transporter'), ('t7', 'Type-7 Transporter'), ('t9', 'Type-9 Heavy'), ('viper3', 'Viper Mk III'), ('viper4', 'Viper Mk IV'), ('vulture', 'Vulture')], max_length=16, verbose_name='Ship Model'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='name',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Ship Name'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='range',
            field=models.FloatField(verbose_name='Jump Range (LY)'),
        ),
    ]
