# Generated by Django 2.0.2 on 2018-03-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180314_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='livery',
            field=models.CharField(default='None', max_length=48, verbose_name='ship livery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commander',
            name='cmdr_name',
            field=models.CharField(max_length=25, verbose_name='Commander Name'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='roster_num',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='DW2 Roster #'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='timezone',
            field=models.CharField(max_length=8, null=True, verbose_name='Timezone'),
        ),
    ]
