# Generated by Django 2.0.2 on 2018-03-20 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180314_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commander',
            name='ship',
        ),
        migrations.AddField(
            model_name='commander',
            name='avg_playtime',
            field=models.CharField(default=-1, max_length=16, verbose_name='Average hours played per week'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commander',
            name='dw_patch',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Maybe')], default=0, verbose_name='Interested in embroidered patch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_01',
            field=models.BooleanField(default=False, verbose_name='Expedition: Nebulae Research Voyages'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_02',
            field=models.BooleanField(default=False, verbose_name='Expedition: REGOR Border Mapping'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_03',
            field=models.BooleanField(default=False, verbose_name='Expedition: Sagittarius-Carina Mission'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_04',
            field=models.BooleanField(default=False, verbose_name='Expedition: Dumbbell Project'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_05',
            field=models.BooleanField(default=False, verbose_name='Expedition: Distant Worlds 3302'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_06',
            field=models.BooleanField(default=False, verbose_name='Expedition: Formidine Rift Survey'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_07',
            field=models.BooleanField(default=False, verbose_name='Expedition: Meet & Greet Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_08',
            field=models.BooleanField(default=False, verbose_name='Expedition: Crab Nebula Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_09',
            field=models.BooleanField(default=False, verbose_name='Expedition: Borderlands Venture'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_10',
            field=models.BooleanField(default=False, verbose_name='Expedition: Western Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_11',
            field=models.BooleanField(default=False, verbose_name='Expedition: August Exodus - A Jaunt To Jaques'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_12',
            field=models.BooleanField(default=False, verbose_name='Expedition: Lost Stars - DWE XBox'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_13',
            field=models.BooleanField(default=False, verbose_name='Expedition: Formidine Rift Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_14',
            field=models.BooleanField(default=False, verbose_name='Expedition: Small Worlds Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_15',
            field=models.BooleanField(default=False, verbose_name='Expedition: Go West'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_16',
            field=models.BooleanField(default=False, verbose_name='Expedition: Galactic Nebula Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_17',
            field=models.BooleanField(default=False, verbose_name='Expedition: Colonia Core Circuit 3302'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_18',
            field=models.BooleanField(default=False, verbose_name='Expedition: Cassiopeia Project'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_19',
            field=models.BooleanField(default=False, verbose_name='Expedition: S.H.E.P.A.R.D. Mission'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_20',
            field=models.BooleanField(default=False, verbose_name='Expedition: Christmas Carriers Convoy'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_21',
            field=models.BooleanField(default=False, verbose_name='Expedition: Distant Stars - Unknown Origins'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_22',
            field=models.BooleanField(default=False, verbose_name='Expedition: Meet & Greet Expedition 2'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_23',
            field=models.BooleanField(default=False, verbose_name='Expedition: Heavy Weight Champions Circuit'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_24',
            field=models.BooleanField(default=False, verbose_name='Expedition: La Grande Expédition Remlok'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_25',
            field=models.BooleanField(default=False, verbose_name='Expedition: Mind The Gap'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_26',
            field=models.BooleanField(default=False, verbose_name='Expedition: Silly Ships Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_27',
            field=models.BooleanField(default=False, verbose_name='Expedition: Pioneers And Explorers'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_28',
            field=models.BooleanField(default=False, verbose_name='Expedition: Mercury 7 Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_29',
            field=models.BooleanField(default=False, verbose_name='Expedition: Helium Hunt'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_30',
            field=models.BooleanField(default=False, verbose_name="Expedition: Helicon's Peak Expedition"),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_31',
            field=models.BooleanField(default=False, verbose_name='Expedition: Local Sightseeing Tour'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_32',
            field=models.BooleanField(default=False, verbose_name='Expedition: Azophi Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_33',
            field=models.BooleanField(default=False, verbose_name='Expedition: Silly Ships Expedition 2'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_34',
            field=models.BooleanField(default=False, verbose_name='Expedition: Summer Great Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_35',
            field=models.BooleanField(default=False, verbose_name='Expedition: Small Worlds Expedition 2'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_36',
            field=models.BooleanField(default=False, verbose_name='Expedition: Monoceros Mission'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_37',
            field=models.BooleanField(default=False, verbose_name='Expedition: Land Of Giants'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_38',
            field=models.BooleanField(default=False, verbose_name='Expedition: Grand Day Out'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_39',
            field=models.BooleanField(default=False, verbose_name='Expedition: Devos Expedition Program #1'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_40',
            field=models.BooleanField(default=False, verbose_name='Expedition: CCN Short Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_41',
            field=models.BooleanField(default=False, verbose_name='Expedition: Miskatonic University Galactic Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_42',
            field=models.BooleanField(default=False, verbose_name="Expedition: Dead End's Circumnavigation Expedition"),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_43',
            field=models.BooleanField(default=False, verbose_name='Expedition: DSN Luxury Tour'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_44',
            field=models.BooleanField(default=False, verbose_name='Expedition: Distant Friends Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_45',
            field=models.BooleanField(default=False, verbose_name='Expedition: Minerva Centaurus Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_46',
            field=models.BooleanField(default=False, verbose_name='Expedition: Christmas Delights'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_47',
            field=models.BooleanField(default=False, verbose_name='Expedition: INRA Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_48',
            field=models.BooleanField(default=False, verbose_name='Expedition: Christmas Carriers Convoy 2'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_49',
            field=models.BooleanField(default=False, verbose_name='Expedition: Orange Run'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_50',
            field=models.BooleanField(default=False, verbose_name='Expedition: Enigma Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_51',
            field=models.BooleanField(default=False, verbose_name='Expedition: Beagle Point Expedition'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_52',
            field=models.BooleanField(default=False, verbose_name='Expedition: Perseus Survey'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_53',
            field=models.BooleanField(default=False, verbose_name='Expedition: Saud Kruger Buoy Tour'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_54',
            field=models.BooleanField(default=False, verbose_name='Expedition: Adder Tour'),
        ),
        migrations.AddField(
            model_name='commander',
            name='exp_55',
            field=models.BooleanField(default=False, verbose_name='Expedition: A Fallen Commander'),
        ),
        migrations.AddField(
            model_name='commander',
            name='livery',
            field=models.CharField(max_length=48, null=True, verbose_name='ship livery'),
        ),
        migrations.AddField(
            model_name='commander',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commander',
            name='ship_id',
            field=models.CharField(default=0, max_length=6, verbose_name='Ship ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commander',
            name='ship_model',
            field=models.CharField(choices=[('adder', 'Adder'), ('conda', 'Anaconda'), ('aspx', 'Asp Explorer'), ('asps', 'Asp Scout'), ('beluga', 'Beluga Liner'), ('chieftain', 'Chieftain'), ('cobra3', 'Cobra Mk III'), ('cobra4', 'Cobra Mk IV'), ('dbx', 'Diamondback Explorer'), ('dbs', 'Diamondback Scout'), ('dolphin', 'Dolphin'), ('eagle', 'Eagle Mk II'), ('fas', 'Federal Assault Ship'), ('corvette', 'Federal Corvette'), ('dropship', 'Federal Dropship'), ('gunship', 'Federal Gunship'), ('fdl', 'Fer-De-Lance'), ('hauler', 'Hauler'), ('clipper', 'Imperial Clipper'), ('courier', 'Imperial Courier'), ('cutter', 'Imperial Cutter'), ('ieagle', 'Imperial Eagle'), ('keelback', 'Keelback'), ('krait', 'Krait'), ('orca', 'Orca'), ('python', 'Python'), ('sidewinder', 'Sidewinder Mk I'), ('t10', 'Type-10 Defender'), ('t6', 'Type-6 Transporter'), ('t7', 'Type-7 Transporter'), ('t9', 'Type-9 Heavy'), ('viper3', 'Viper Mk III'), ('viper4', 'Viper Mk IV'), ('vulture', 'Vulture')], default='aspx', max_length=16, verbose_name='Ship Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commander',
            name='ship_name',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Ship Name'),
        ),
        migrations.AddField(
            model_name='commander',
            name='ship_range',
            field=models.FloatField(default=0, verbose_name='Jump Range (LY)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commander',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Expedition staff'),
        ),
        migrations.AddField(
            model_name='commander',
            name='validation',
            field=models.BooleanField(default=True, verbose_name='Validated'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='platform',
            field=models.CharField(choices=[(0, 'PC'), (1, 'XBOne'), (2, 'PS4'), (3, 'Mac')], default='PC', max_length=8, verbose_name='Platform'),
        ),
        migrations.DeleteModel(
            name='Ship',
        ),
    ]
