# Generated by Django 2.0.2 on 2018-03-21 22:04

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180321_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commander',
            name='applicant_num',
        ),
        migrations.AlterField(
            model_name='commander',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='App. #'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='platform',
            field=models.CharField(choices=[('PC', 0), ('XBOX', 1), ('PS4', 2), ('MAC', 3)], default=core.models.Commander.Platform(0), max_length=8, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='role1',
            field=models.IntegerField(choices=[('EXPL', 0), ('RAT', 1), ('MINER', 2), ('MECH', 3), ('GUIDE', 4), ('PHOTO', 5), ('ESCORT', 6), ('GEOL', 7), ('SCI', 8), ('MEDIA', 9), ('MCORP', 10), ('LOGIST', 11)], default=core.models.Commander.Role(0), verbose_name='Primary Role'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='role2',
            field=models.IntegerField(choices=[('EXPL', 0), ('RAT', 1), ('MINER', 2), ('MECH', 3), ('GUIDE', 4), ('PHOTO', 5), ('ESCORT', 6), ('GEOL', 7), ('SCI', 8), ('MEDIA', 9), ('MCORP', 10), ('LOGIST', 11)], null=True, verbose_name='Secondary Role'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='ship_model',
            field=models.CharField(choices=[('ADDER', 'adder'), ('ANACONDA', 'conda'), ('ASP_EXPLORER', 'aspx'), ('ASP_SCOUT', 'asps'), ('BELUGA', 'beluga'), ('CHIEFTAIN', 'chieftain'), ('COBRA_MK_III', 'cobra3'), ('COBRA_MK_IV', 'cobra4'), ('DIAMONDBACK_EXPLORER', 'dbx'), ('DIAMONDBACK_SCOUT', 'dbs'), ('DOLPHIN', 'dolphin'), ('EAGLE', 'eagle'), ('FEDERAL_ASSAULT_SHIP', 'fas'), ('FEDERAL_CORVETTE', 'corvette'), ('FEDERAL_DROPSHIP', 'dropship'), ('FEDERAL_GUNSHIP', 'gunship'), ('FER_DE_LANCE', 'fdl'), ('HAULER', 'hauler'), ('IMPERIAL_CLIPPER', 'clipper'), ('IMPERIAL_COURIER', 'courier'), ('IMPERIAL_CUTTER', 'cutter'), ('IMPERIAL_EAGLE', 'ieagle'), ('KEELBACK', 'keelback'), ('KRAIT', 'krait'), ('ORCA', 'orca'), ('PYTHON', 'python'), ('SIDEWINDER', 'sidewinder'), ('TYPE_10', 't10'), ('TYPE_6', 't6'), ('TYPE_7', 't7'), ('TYPE_9', 't9'), ('VIPER_MK_III', 'viper3'), ('VIPER_MK_IV', 'viper4'), ('VULTURE', 'vulture')], max_length=16, verbose_name='Ship Model'),
        ),
    ]
