# Generated by Django 2.0.2 on 2018-03-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0008_auto_20180321_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commander',
            old_name='id',
            new_name='application_num',
        ),
        migrations.AlterField(
            model_name='commander',
            name='platform',
            field=models.CharField(choices=[('PC', 0), ('XBOX', 1), ('PS4', 2), ('MAC', 3)], default=0, max_length=8, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='role1',
            field=models.IntegerField(choices=[('EXPL', 0), ('RAT', 1), ('MINER', 2), ('MECH', 3), ('GUIDE', 4), ('PHOTO', 5), ('ESCORT', 6), ('GEOL', 7), ('SCI', 8), ('MEDIA', 9), ('MCORP', 10), ('LOGIST', 11)], default=0, verbose_name='Primary Role'),
        ),
    ]
