# Generated by Django 2.0.2 on 2018-03-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180321_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='commander',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commander',
            name='application_num',
            field=models.PositiveIntegerField(verbose_name='App. #'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='roster_num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='DW2 Roster #'),
            preserve_default=False,
        ),
    ]
