# Generated by Django 2.0.2 on 2018-03-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180321_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='commander',
            name='ship_showcase_link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Showcase Image Link'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='roster_num',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='DW2 Roster #'),
        ),
    ]
