# Generated by Django 2.0.2 on 2018-03-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180322_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='role1',
            field=models.IntegerField(choices=[(0, 'Explorer'), (1, 'Fuel Rat'), (2, 'Miner'), (3, 'Fleet Mechanic'), (4, 'Tour Guide'), (5, 'Photographer'), (6, 'Fighter Escort'), (7, 'Geologist'), (8, 'Scientist'), (9, 'Media'), (10, 'MediCorp'), (11, 'Fleet Logistics')], default=0, verbose_name='Primary Role'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='role2',
            field=models.IntegerField(choices=[(0, 'Explorer'), (1, 'Fuel Rat'), (2, 'Miner'), (3, 'Fleet Mechanic'), (4, 'Tour Guide'), (5, 'Photographer'), (6, 'Fighter Escort'), (7, 'Geologist'), (8, 'Scientist'), (9, 'Media'), (10, 'MediCorp'), (11, 'Fleet Logistics')], null=True, verbose_name='Secondary Role'),
        ),
    ]
