# Generated by Django 2.0.2 on 2018-03-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180323_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='ship_model',
            field=models.CharField(choices=[('adder', 'Adder'), ('conda', 'Anaconda'), ('aspx', 'Asp Explorer'), ('asps', 'Asp Scout'), ('beluga', 'Beluga'), ('chieftain', 'Alliance Chieftain'), ('cobra3', 'Cobra Mk. III'), ('cobra4', 'Cobra Mk. IV'), ('dbx', 'Diamondback Explorer'), ('dbs', 'Diamondback Scout'), ('dolphin', 'Dolphin'), ('eagle', 'Eagle'), ('fas', 'Federal Assault Ship'), ('corvette', 'Federal Corvette'), ('dropship', 'Federal Dropship'), ('gunship', 'Federal Gunship'), ('fdl', 'Fer-De-Lance'), ('hauler', 'Hauler'), ('clipper', 'Imperial Clipper'), ('courier', 'Imperial Courier'), ('cutter', 'Imperial Cutter'), ('ieagle', 'Imperial Eagle'), ('keelback', 'Keelback'), ('krait', 'Krait'), ('orca', 'Orca'), ('python', 'Python'), ('sidewinder', 'Sidewinder'), ('t10', 'Type-10 Defender'), ('t6', 'Type-6 Transporter'), ('t7', 'Type-7 Transporter'), ('t9', 'Type-9 Heavy'), ('viper3', 'Viper Mk. III'), ('viper4', 'Viper Mk. IV'), ('vulture', 'Vulture')], max_length=16, verbose_name='Ship Model'),
        ),
    ]
