# Generated by Django 2.0.2 on 2018-03-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180323_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='platform',
            field=models.CharField(choices=[('PC', 'PC'), ('XBOne', 'Xbox One'), ('PS4', 'PlayStation 4'), ('Mac', 'Mac')], default='PC', max_length=8, verbose_name='Platform'),
        ),
    ]
