# Generated by Django 2.0.2 on 2018-02-02 06:50

import django.db.models.deletion
from django.db import migrations, models

import astrophotography.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1sum', models.CharField(blank=True, max_length=40, unique=True)),
                ('file', models.ImageField(upload_to=astrophotography.models.Image.waypoint_folder)),
                ('orig_filename', models.CharField(blank=True, max_length=768, verbose_name='original filename')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('desc', models.CharField(blank=True, max_length=768, null=True, verbose_name='description')),
                ('public', models.BooleanField(default=False)),
                ('contest_entry', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, max_length=32, null=True)),
                ('subsector', models.CharField(blank=True, max_length=32, null=True)),
                ('system', models.CharField(max_length=128)),
                ('body', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='astrophotography.Location'),
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Commander'),
        ),
    ]
