# Generated by Django 2.0.2 on 2018-02-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrophotography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sha1sum',
            field=models.CharField(blank=True, editable=False, max_length=40, unique=True),
        ),
    ]
