# Generated by Django 2.0.2 on 2018-02-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrophotography', '0002_auto_20180202_2057'),
    ]

    operations = [
        migrations.RenameField('Image', 'file', 'image'),
    ]
