# Generated by Django 2.0.2 on 2018-02-09 03:44

import django.db.models.deletion
from django.db import migrations, models

import astrophotography.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180209_0344'),
        ('astrophotography', '0003_auto_20180208_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='contest_entry',
        ),
        migrations.AddField(
            model_name='image',
            name='thumb',
            field=models.ImageField(null=True, upload_to='thumbs'),
        ),
        migrations.AddField(
            model_name='image',
            name='waypoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Waypoint'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=astrophotography.models.Image.waypoint_folder),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Location'),
        ),
        migrations.AlterField(
            model_name='image',
            name='orig_filename',
            field=models.CharField(max_length=768, verbose_name='original filename'),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Commander'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
