# Generated by Django 2.0.2 on 2018-03-25 18:10

from django.db import migrations, models

import astrophotography.models


class Migration(migrations.Migration):

    dependencies = [
        ('astrophotography', '0005_auto_20180222_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_height',
            field=models.IntegerField(default=0, verbose_name='image height'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='img_width',
            field=models.IntegerField(default=0, verbose_name='image width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='processed by image utilities'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field=models.IntegerField(verbose_name='image height'), upload_to=astrophotography.models.Image.waypoint_folder, width_field=models.IntegerField(verbose_name='image width')),
        ),
    ]
