# Generated by Django 2.0.2 on 2018-03-25 18:43

from django.db import migrations, models

import astrophotography.models


class Migration(migrations.Migration):

    dependencies = [
        ('astrophotography', '0006_auto_20180325_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='img_height', upload_to=astrophotography.models.Image.waypoint_folder, width_field='img_width'),
        ),
    ]
