# Generated by Django 2.0.2 on 2018-03-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrophotography', '0007_auto_20180325_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='image',
            name='del_hash',
            field=models.CharField(max_length=512, null=True, verbose_name='imgur deletion hash'),
        ),
        migrations.AlterField(
            model_name='image',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='edited'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgur_url',
            field=models.CharField(max_length=512, null=True, verbose_name='link to imgur upload'),
        ),
        migrations.AlterField(
            model_name='image',
            name='public',
            field=models.BooleanField(default=False, verbose_name='display publicly'),
        ),
    ]
