# Generated by Django 2.0.2 on 2018-03-28 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrophotography', '0009_auto_20180326_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='processed',
        ),
    ]
