# Generated by Django 2.0.2 on 2018-03-29 02:32

import sorl.thumbnail.fields
from django.db import migrations, models

import astrophotography.models


class Migration(migrations.Migration):

    dependencies = [
        ('astrophotography', '0010_remove_image_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(height_field='img_height', upload_to=astrophotography.models.Image.waypoint_folder, width_field='img_width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public'),
        ),
    ]
